CREATE TABLE IF NOT EXISTS `users`
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `email` VARCHAR (128) NOT NULL,
  `password` VARCHAR (128) NOT NULL,
  `created_at` TIMESTAMP DEFAULT 0,
  `updated_at` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`email`)
);

INSERT INTO `users` VALUES (DEFAULT, 'admin@frameworx.dev', '$2y$10$alSAjighpBDZ6mPz9Nx1n.EONB6B5Fkq387mVE907FGmll7aamKSG', DEFAULT, DEFAULT);
